# render.yaml (repo root)
services:
  - type: web
    runtime: docker
    name: my-backend
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    runtime: docker
    name: my-frontend
    rootDir: frontend
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      # Use backend's externally reachable URL
      - key: NEXT_PUBLIC_FRONTEND_URL
        fromService:
          name: my-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      